# Generated by Django 4.1.1 on 2022-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldlog', '0002_alter_weldlog_fitupdate_alter_weldlog_pwhtdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weldlog',
            name='fitupdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weldlog',
            name='pwhtdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weldlog',
            name='rtdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weldlog',
            name='vtdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
