# Generated by Django 4.1.1 on 2022-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldlog', '0003_alter_weldlog_fitupdate_alter_weldlog_pwhtdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldlog',
            name='pwhtrate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weldlog',
            name='rtrate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
